# Generated by Django 4.2.27 on 2026-02-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_rename_created_on_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upDated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
