
# Generated by Django 4.2.27 on 2026-02-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='upDated_on',
            new_name='updated_on',
        ),
        migrations.AddField(
            model_name='comment',
            name='Field_2',
            field=models.CharField(default='Hello world!'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Field_3',
            field=models.CharField(null=True),
        ),
    ]
