# Generated by Django 4.2.27 on 2026-02-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Field_2',
            field=models.CharField(default="HelloWorld!"),
        ),
    ]
