# Generated by Django 4.2.27 on 2026-02-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='excerpt',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
